"""Leakage-safe train/test splitting for uncertainty samples."""

from __future__ import annotations

import numpy as np


def split_samples(samples: np.ndarray, n_train: int, seed: int | None = None) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Randomly split along the first axis and return the training indices.

    The permutation is generated by a local :class:`numpy.random.Generator`,
    so the split does not consume or depend on NumPy's process-global random
    state.  The returned arrays are independent copies and preserve all
    trailing dimensions.  ``n_train`` must be strictly between zero and the
    number of observations.  The complement of the returned indices is the
    test set, in the order used for ``test``.
    """
    x = np.asarray(samples)
    if x.ndim == 0 or x.shape[0] < 2:
        raise ValueError("samples must contain at least two observations")
    if isinstance(n_train, bool) or not isinstance(n_train, (int, np.integer)):
        raise ValueError("n_train must be an integer")
    if not 0 < int(n_train) < x.shape[0]:
        raise ValueError("n_train must satisfy 0 < n_train < number of samples")
    if isinstance(seed, (bool, np.bool_)):
        raise ValueError("seed must be an integer or None, not bool")
    if seed is not None and not isinstance(seed, (int, np.integer)):
        raise TypeError("seed must be an integer or None")
    idx = np.random.default_rng(None if seed is None else int(seed)).permutation(x.shape[0])
    train_idx = idx[: int(n_train)]
    test_idx = idx[int(n_train):]
    return x[train_idx].copy(), x[test_idx].copy(), train_idx.copy()
